project:
  type: website
  output-dir: docs

website:
  title: "Analise de correspondencia"
  navbar:
    left:
      - href: index.qmd
        text: ANACOR
      - href: show.qmd
        text: Artigo

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



